### ISSUE TITLE
openapi 3.1 support

### ISSUE THREAD

**Issue by maxgurewitz** [fastify/fastify-swagger-ui#67]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hi all. This project doesn't seem to support openapi 3.1.

<img width="1840" alt="Screen Shot 2023-05-29 at 10 13 17 PM" src="https://github.com/fastify/fastify-swagger-ui/assets/1750599/ece3e32c-536a-4a69-a4aa-478a9651f855">

However swagger-ui seems to support openapi 3.1.

https://github.com/swagger-api/swagger-ui/pull/8367/files

Is addressing this easy? Thank you.

**Comment by Uzlopak** [comment]
Well you could just patch the version check, but we need to check what the differences are and maybe see if the new features are handled properly.

**Comment by mcollina** [comment]
We should update to swagger-ui v5, but I'm not sure this was released  yet.

**Comment by qqilihq** [comment]
[Swagger UI 5.0.0](https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0) is available since a few hours.

We've already been using a patched `fastify-swagger-ui` library during the last few weeks, which worked fine for us. In case anybody is interested for the time being, I've just updated it to use the final swagger-ui v5.0.0

NPM: `@lineupr/fastify-swagger-ui`
GitHub: https://github.com/LineUpr/fastify-swagger-ui

**Comment by Uzlopak** [comment]
@qqilihq 

Ok, dependabot merged automatically swagger-ui. Does anything needs to be patched?

**Comment by qqilihq** [comment]
@Uzlopak Just changing to `"swagger-ui-dist": "5.0.0"` was sufficient for us.

**Comment by mcollina** [comment]
I've just shipped v1.9.0.
